fixes:
  - "io/ballerina/stdlib/mcp/plugin/::./compiler-plugin/src/main/java/io/ballerina/stdlib/mcp/plugin/"
  - "ballerina/mcp/**/::../ballerina/"

ignore:
  - "ballerina-tests"

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
