[package]
org = "ballerina"
name = "mcp_crypto_client"
version = "0.1.0"
distribution = "2201.13.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mcp"
version = "2.0.0"
